let classMembers=[];const rotatedIndexes=new Set([7,9,10,11,13,17,22,26,29,30,32,33,34,35]);let unlockedProfiles=JSON.parse(localStorage.getItem('k116_unlocked'))||[];const allVideos=[{year:'10',title:'Tổng kết Học kỳ 1 Lớp 10.avi',url:'https://drive.google.com/file/d/1pA5L1-iRBe6eXJK_xd3icQZwf1QIcN8M/preview'},{year:'10',title:'Tổng kết Học kỳ 2 Lớp 10.avi',url:'https://drive.google.com/file/d/1nAQwl-jt2B1xMMvHaxN0Ze7txjhgpFbh/preview'},{year:'10',title:'Hoạt động hè Lớp 10.mp4',url:'https://drive.google.com/file/d/1BehlBjCk0VUYqDE4hQhrsfwVM_ATEv2U/preview'},{year:'11',title:'Kỉ niệm 20-10 Lớp 11.mov',url:'https://drive.google.com/file/d/19_DI1Bm-sRSyZgNlQYsklLq12nbb4GTy/preview'},{year:'11',title:'Tổng kết Học kỳ 1 Lớp 11.avi',url:'https://drive.google.com/file/d/1YFr9yseJmZwirGHuHhf8n9usEDd7Qg0T/preview'},{year:'11',title:'Tổng kết Học kỳ 2 Lớp 11.mp4',url:'https://drive.google.com/file/d/1NUkWFHIQ5FwemPcUNbwIjlO4vrWkjNxu/preview'},{year:'12',title:'Kỉ niệm 20-10 Lớp 12.mp4',url:'https://drive.google.com/file/d/1oTq1TslUmekd-4Xn59cuJuvjUare1CuD/preview'},{year:'12',title:'Tổng kết Học kỳ 1 Lớp 12.avi',url:'https://drive.google.com/file/d/1uCDLcppKrdvCbBD8ElzseAJu17Qf_Izs/preview'},{year:'12',title:'Tổng kết Lớp 12 (Coming Soon).avi',url:'about:blank'}];function showRetroAlert(title,msg,onConfirmStr){document.getElementById('retro-alert-title').innerText=title;document.getElementById('retro-alert-msg').innerHTML=msg;let btnHtml=`<button class="btn-retro" onclick="closeRetroAlert()">Đồng ý</button>`;if(onConfirmStr){btnHtml=`<button class="btn-retro" style="background: var(--persica-red); color: white; margin-right: 10px;" onclick="${onConfirmStr}">Xác nhận</button> <button class="btn-retro" onclick="closeRetroAlert()">Hủy</button>`}
document.getElementById('retro-alert-buttons').innerHTML=btnHtml;document.getElementById('retro-alert').style.display='flex'}
function closeRetroAlert(){document.getElementById('retro-alert').style.display='none'}
async function loadData(){try{const response=await fetch('data.txt');if(!response.ok)throw new Error("File data.txt not found");const text=await response.text();const lines=text.split('\n').filter(l=>l.trim()!=='');classMembers=lines.map((line,index)=>{const[fileName,dob,email,zodiac]=line.split('|');let name=fileName.trim().replace(/^\d+\.\s*/,'').replace(/\.webp$/i,'');let display=name;let words=name.split(' ');if(words.length>3)display=words.slice(0,2).join(' ')+'<br>'+words.slice(2).join(' ');return{isTeacher:!1,fileName:fileName.trim(),cleanName:name,displayName:display,dob:dob.trim(),email:email.trim(),zodiac:zodiac.trim(),avatar:`12 Tin/${fileName.trim()}`,rotate:rotatedIndexes.has(index+1)}});classMembers.unshift({isTeacher:!0,cleanName:'Cô Phạm Thị Thùy Linh',displayName:'Cô Phạm Thị<br>Thùy Linh',avatar:'12 Tin/goc_chu_nhiem.webp',rotate:!1});renderMembers();initMinesweeper();initTTT()}catch(e){document.getElementById('members-grid').innerHTML="<p style='color:red'>Dùng Live Server để load file data.txt nhé!</p>"}}
function renderMembers(){const grid=document.getElementById('members-grid');if(!grid)return;let html='';classMembers.forEach((member,i)=>{const isUnlocked=member.isTeacher||unlockedProfiles.includes(i);const lockedClass=isUnlocked?'':'locked';const displayName=isUnlocked?member.displayName:'Hồ sơ<br>Bảo mật';const action=isUnlocked?`openProfileModal(${i})`:`showRetroAlert('BẢO MẬT K116 TIN', 'Hồ sơ đang bị khóa!<br>Hãy sang tab 🎮 Giải cứu chơi game để mở khóa nhé.')`;html+=`
        <div class="member-icon ${lockedClass}" onclick="${action}">
            <div class="img-box" style="${member.isTeacher ? 'border-color: var(--yellow-neon);' : ''}">
                <img src="${member.avatar}" alt="Member" loading="lazy" class="${member.rotate ? 'rotate' : ''}" onerror="this.src='https://via.placeholder.com/90x120/cccccc?text=?'">
            </div>
            <p class="name" style="${member.isTeacher ? 'background: var(--yellow-neon); color: #000;' : ''}">${displayName}</p>
        </div>`});grid.innerHTML=html}
function unlockProfiles(count){let lockedIndexes=[];for(let i=1;i<classMembers.length;i++){if(!unlockedProfiles.includes(i))lockedIndexes.push(i);}
if(lockedIndexes.length===0){showRetroAlert("🎉 HOÀN THÀNH","Bạn đã mở khóa toàn bộ 35 thành viên lớp K116 TIN!");return}
let unlockedNow=[];for(let i=0;i<count;i++){if(lockedIndexes.length>0){let rIdx=Math.floor(Math.random()*lockedIndexes.length);let pIdx=lockedIndexes.splice(rIdx,1)[0];unlockedProfiles.push(pIdx);unlockedNow.push(classMembers[pIdx].cleanName)}}
localStorage.setItem('k116_unlocked',JSON.stringify(unlockedProfiles));renderMembers();showRetroAlert("ĐÃ THẮNG!",`Mở khóa thành công:<br><br><span style="color: var(--persica-red); font-size: 1.2rem;">${unlockedNow.join('<br>')}</span>`)}
function resetUnlocks(){showRetroAlert("XÁC NHẬN","Bạn có chắc muốn KHÓA LẠI toàn bộ hồ sơ lớp không?","confirmReset()")}
function confirmReset(){unlockedProfiles=[];localStorage.removeItem('k116_unlocked');renderMembers();closeRetroAlert()}
const totalPhotos=215;const photoFolder='rm';const photoExtension='.webp';function renderRandomPhotos(){const grid=document.getElementById('photos-grid');if(!grid)return;let randomIndexes=new Set();const limit=totalPhotos<6?totalPhotos:6;while(randomIndexes.size<limit){let randomNum=Math.floor(Math.random()*totalPhotos)+1;randomIndexes.add(randomNum)}
let html='';let isOdd=!0;randomIndexes.forEach(index=>{let rotationClass=isOdd?'film':'';html+=`
            <div class="photo-item ${rotationClass}" onclick="openImgModal('${photoFolder}/${index}${photoExtension}')">
                <img src="${photoFolder}/${index}${photoExtension}" alt="Moment" loading="lazy" style="width: 100%; height: 100%; object-fit: cover; border: 2px solid #000;">
            </div>
        `;isOdd=!isOdd});grid.innerHTML=html}
function playRPS(playerChoice){const choices=['Búa','Bao','Kéo'];const aiChoice=choices[Math.floor(Math.random()*3)];const resEl=document.getElementById('rps-result');if(playerChoice===aiChoice){resEl.innerText='Hòa!';resEl.style.color='var(--yellow-neon)'}else if((playerChoice==='Búa'&&aiChoice==='Kéo')||(playerChoice==='Bao'&&aiChoice==='Búa')||(playerChoice==='Kéo'&&aiChoice==='Bao')){resEl.innerText='Thắng!';resEl.style.color='#0f0';unlockProfiles(1)}else{resEl.innerText='Thua!';resEl.style.color='var(--persica-red)'}}
let tttBoard=['','','','','','','','',''];let tttGameOver=!1;function initTTT(){tttBoard=['','','','','','','','',''];tttGameOver=!1;document.getElementById('ttt-result').innerText='Lượt của bạn (X)';document.getElementById('ttt-result').style.color='#0f0';renderTTT()}
function renderTTT(){document.getElementById('ttt-grid').innerHTML=tttBoard.map((val,i)=>`<div class="ttt-cell ${val}" onclick="tttClick(${i})">${val}</div>`).join('')}
function checkTTTWin(p){const wins=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];return wins.some(combo=>combo.every(i=>tttBoard[i]===p))}
function tttClick(idx){if(tttGameOver||tttBoard[idx]!=='')return;tttBoard[idx]='X';renderTTT();if(checkTTTWin('X')){tttGameOver=!0;document.getElementById('ttt-result').innerText='Đã thắng!';document.getElementById('ttt-result').style.color='#0f0';setTimeout(()=>unlockProfiles(2),200);return}
if(!tttBoard.includes('')){tttGameOver=!0;document.getElementById('ttt-result').innerText='Hòa cờ!';document.getElementById('ttt-result').style.color='var(--yellow-neon)';return}
document.getElementById('ttt-result').innerText='AI đang nghĩ...';document.getElementById('ttt-result').style.color='#fff';setTimeout(()=>{let empty=[];tttBoard.forEach((v,i)=>{if(v==='')empty.push(i)});let aiMove=empty[Math.floor(Math.random()*empty.length)];tttBoard[aiMove]='O';renderTTT();if(checkTTTWin('O')){tttGameOver=!0;document.getElementById('ttt-result').innerText='Thua rồi!';document.getElementById('ttt-result').style.color='var(--persica-red)'}else{document.getElementById('ttt-result').innerText='Lượt của bạn (X)';document.getElementById('ttt-result').style.color='#0f0'}},200)}
let msBoard=[];const msRows=5,msCols=5,msMines=3;let msGameOver=!1,msRevealedCount=0;function initMinesweeper(){msBoard=[];msGameOver=!1;msRevealedCount=0;for(let r=0;r<msRows;r++){msBoard[r]=[];for(let c=0;c<msCols;c++)msBoard[r][c]={mine:!1,revealed:!1,flagged:!1,count:0}}
document.getElementById('ms-reset').innerText='🙂';document.getElementById('mine-count').innerText=msMines.toString().padStart(2,'0');let placed=0;while(placed<msMines){let r=Math.floor(Math.random()*msRows),c=Math.floor(Math.random()*msCols);if(!msBoard[r][c].mine){msBoard[r][c].mine=!0;placed++}}
for(let r=0;r<msRows;r++){for(let c=0;c<msCols;c++){if(!msBoard[r][c].mine){let count=0;for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){let nr=r+dr,nc=c+dc;if(nr>=0&&nr<msRows&&nc>=0&&nc<msCols&&msBoard[nr][nc].mine)count++}
msBoard[r][c].count=count}}}
renderMinesweeper()}
function renderMinesweeper(){let html='';for(let r=0;r<msRows;r++){for(let c=0;c<msCols;c++){let cell=msBoard[r][c],content='',classes='ms-cell';if(cell.revealed){classes+=' revealed';if(cell.mine)content='💣';else if(cell.count>0)content=`<span class="c${cell.count}">${cell.count}</span>`}else if(cell.flagged)content='🚩';html+=`<div class="${classes}" onclick="msClick(${r},${c})" oncontextmenu="msRightClick(event, ${r},${c})">${content}</div>`}}
document.getElementById('ms-grid').innerHTML=html}
function msClick(r,c){if(msGameOver||msBoard[r][c].revealed||msBoard[r][c].flagged)return;if(msBoard[r][c].mine){msGameOver=!0;document.getElementById('ms-reset').innerText='😵';for(let i=0;i<msRows;i++)for(let j=0;j<msCols;j++)if(msBoard[i][j].mine)msBoard[i][j].revealed=!0;renderMinesweeper();return}
msRevealRecursive(r,c);renderMinesweeper();checkMsWin()}
function msRightClick(e,r,c){e.preventDefault();if(msGameOver||msBoard[r][c].revealed)return;msBoard[r][c].flagged=!msBoard[r][c].flagged;let currentFlags=parseInt(document.getElementById('mine-count').innerText);document.getElementById('mine-count').innerText=(msBoard[r][c].flagged?currentFlags-1:currentFlags+1).toString().padStart(2,'0');renderMinesweeper()}
function msRevealRecursive(r,c){if(r<0||r>=msRows||c<0||c>=msCols)return;let cell=msBoard[r][c];if(cell.revealed||cell.flagged||cell.mine)return;cell.revealed=!0;msRevealedCount++;if(cell.count===0)for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)msRevealRecursive(r+dr,c+dc);}
function checkMsWin(){if(msRevealedCount===(msRows*msCols-msMines)){msGameOver=!0;document.getElementById('ms-reset').innerText='😎';setTimeout(()=>unlockProfiles(3),200)}}
let isTypingStarted=!1;let typingTimer;function startTypingTribute(){const el=document.getElementById('typing-text');if(el.innerHTML.length>0)return;isTypingStarted=!0;clearTimeout(typingTimer);const text="Gửi cô Linh của chúng con!\n\nTrong hành trình 1000 ngày rực nắng, nếu thanh xuân của chúng con là một chuyến tàu, thì cô chính là người lặng lẽ cầm lái chuyến đi cảm xúc ấy. Cô Linh không chỉ cho chúng con con chữ, bài học quý giá mà cô còn gieo vào lòng 35 cô, cậu học trò nhỏ hạt mầm của niềm tin, sự bền bỉ và tình yêu thương vô bờ. Từ tận đáy lòng, tập thể lớp K116 Tin xin gửi lời cảm ơn chân thành vì sự đồng hành bền bỉ, không biết mệt mỏi của cô - người thuyền trưởng thầm lặng đưa đoàn tàu thanh xuân của chúng con đi đến với sân ga của ước mơ và khát vọng.\n\nChúng mình đã “lớn lên” tại Chu Ba đầy nắng vàng và hạnh phúc như vậy đấy. Hy vọng rằng 35 mảnh ghép, 35 con người tập thể K116 Tin, với hành trang là tri thức, hoài bão và khát vọng, sẽ bay cao, bay xa trên hành trình kiếm tìm chiếc chìa khóa mở ra cánh cửa tương lai.";let i=0;el.innerHTML='';function typeWriter(){if(i<text.length){el.innerHTML+=text.charAt(i)==='\n'?'<br>':text.charAt(i);i++;typingTimer=setTimeout(typeWriter,30)}}
typeWriter()}
function filterVideos(year){const grid=document.getElementById('video-file-grid');if(!grid)return;document.querySelectorAll('.folder-item').forEach(el=>el.classList.remove('active'));document.getElementById(`folder-${year}`).classList.add('active');const filtered=year==='all'?allVideos:allVideos.filter(v=>v.year===year);document.getElementById('item-count').innerText=`${filtered.length} items`;grid.innerHTML=filtered.map(v=>{if(v.title.includes("Coming Soon")){return `
                <div class="video-file" style="opacity: 0.5; cursor: not-allowed;" onclick="showRetroAlert('Thông báo', 'Video này đang được hoàn thiện. Hãy quay lại sau nhé!')">
                    <span class="file-icon">⏳</span><span class="file-name">${v.title}</span>
                </div>
            `}else{return `
                <div class="video-file" onclick="openVideoModal('${v.url}', '${v.title}')">
                    <span class="file-icon">🎬</span><span class="file-name">${v.title}</span>
                </div>
            `}}).join('')}
function openProfileModal(i){const m=classMembers[i];const modal=document.getElementById('img-modal');if(!modal)return;let infoHTML=m.isTeacher?`<div id="modal-caption" style="box-shadow: 6px 6px 0 var(--yellow-neon); position: relative; background: #fff; padding: 20px; border: 4px solid var(--border-color); flex-grow: 1; text-align: left;"><h2 style="color: var(--pink-neon); text-align: center; font-family: 'VT323', monospace; font-size: 2.5rem; margin-bottom: 10px; border-bottom: 2px dashed #000; padding-bottom: 10px;">${m.cleanName}</h2><ul style="list-style-type: none; padding: 0; margin-top: 15px;"><li style="background: #fef3c7; border: 2px solid #ff4d4d; color: #b45309; font-weight: bold; padding: 10px; margin-bottom: 10px; border-radius: 8px;">🙂 "ai đăng ký thủ khoa nhắn cô nhé"</li><li style="background: #e6f2ff; border: 1px solid #000; padding: 10px; margin-bottom: 10px; border-radius: 8px;">"bằng tất cả nghiệp vụ của mình"</li><li style="background: #e6ffe6; border: 1px solid #000; padding: 10px; margin-bottom: 10px; border-radius: 8px;">"bằng mọi giá phải được xuất sắc"</li><li style="background: #cc0000; color: #ffffff; border: 2px solid #000; font-weight: bold; padding: 10px; margin-bottom: 10px; border-radius: 8px;">😡 "hãy để tuổi già chúng tôi được yên ổn"</li></ul></div>`:`<div id="modal-caption" style="box-shadow: 6px 6px 0 var(--blue-neon); background: #fff; padding: 20px; border: 4px solid var(--border-color); flex-grow: 1; text-align: left;"><h2 style="color: var(--blue-neon); text-align: center; text-shadow: 1px 1px 0 #000; font-family: 'VT323', monospace; font-size: 2.5rem; margin-bottom: 10px; border-bottom: 2px dashed #000; padding-bottom: 10px;">${m.cleanName}</h2><div style="font-family: 'Courier Prime', monospace; font-size: 1rem; margin-top: 15px;"><p style="background: #e1f5fe; border: 2px solid #000; padding: 10px; border-radius: 8px; margin-bottom: 10px; box-shadow: 2px 2px 0 #000;"><strong>🎂 Sinh nhật:</strong> ${m.dob}</p><p style="background: #fff9c4; border: 2px solid #000; padding: 10px; border-radius: 8px; margin-bottom: 10px; box-shadow: 2px 2px 0 #000;"><strong>✨ Cung Hoàng Đạo:</strong> ${m.zodiac}</p><p style="background: #fce4ec; border: 2px solid #000; padding: 10px; border-radius: 8px; box-shadow: 2px 2px 0 #000; word-break: break-all;"><strong>📧 Liên hệ:</strong> <a href="mailto:${m.email}" style="color: var(--bg-desktop); font-weight: bold;">${m.email}</a></p></div></div>`;modal.innerHTML=`<span class="close-modal" onclick="closeModal()">&times;</span><div class="modal-content-wrapper"><div class="modal-img-container"><img src="${m.avatar}" class="${m.rotate ? 'rotate' : ''}"></div>${infoHTML}</div>`;modal.style.display='flex'}
function openImgModal(imgSrc){const modal=document.getElementById('img-modal');if(!modal)return;modal.innerHTML=`
        <span class="close-modal" onclick="closeModal()">&times;</span>
        <div class="modal-content-wrapper">
            <div class="modal-img-container" style="max-width: 90vw; max-height: 90vh;">
                <img src="${imgSrc}" style="width: auto; height: auto; max-width: 100%; max-height: 80vh; border: 8px solid #fff; box-shadow: 10px 10px 0 var(--pink-neon);">
            </div>
        </div>
    `;modal.style.display='flex'}
function openVideoModal(videoUrl,videoTitle){const modal=document.getElementById('img-modal');if(!modal)return;modal.innerHTML=`<span class="close-modal" onclick="closeModal()">&times;</span><div class="modal-content-wrapper" style="flex-direction: column; max-width: 800px; width: 100%;"><div id="modal-caption" style="width: 100%; text-align: center; box-shadow: 6px 6px 0 var(--pink-neon); margin-bottom: 15px; background: #fff; padding: 10px; border: 4px solid var(--border-color);"><h2 style="font-family: 'VT323', monospace; color: var(--pink-neon); margin: 0; font-size: 2rem; text-shadow: none; border: none; padding: 0;">${videoTitle}</h2></div><div style="width: 100%; position: relative; padding-bottom: 56.25%; height: 0; border: 4px solid #000; box-shadow: 6px 6px 0 var(--blue-neon); background: #000;"><iframe style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" src="${videoUrl}" title="${videoTitle}" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div></div>`;modal.style.display='flex'}
function closeModal(){document.getElementById('img-modal').style.display='none'}
function openTab(evt,tabId,urlPath){document.querySelectorAll(".tab-content").forEach(el=>el.style.display="none");document.querySelectorAll(".tab").forEach(el=>el.classList.remove("active"));const tabElement=document.getElementById(tabId);tabElement.style.display=(tabId==='tab-videos')?"flex":"block";evt.currentTarget.classList.add("active");document.getElementById("main-window-url").value="https://12tinthichcodelinhtinh.codes/"+urlPath;if(tabId==='tab-trian')startTypingTribute();if(tabId==='tab-photos')renderRandomPhotos();}
document.addEventListener('DOMContentLoaded',()=>{loadData();filterVideos('all');startTypingTribute()})
